name: CI/CD pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag h4rkon/tracker-app:${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push h4rkon/tracker-app:${{ github.sha }}
          docker tag h4rkon/tracker-app:${{ github.sha }} h4rkon/tracker-app:latest
          docker push h4rkon/tracker-app:latest
